# Generated by Django 6.0.2 on 2026-10-01 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_mode',
            field=models.CharField(choices=[('aspirant', 'Aspirant'), ('university', 'University')], default='aspirant', help_text='The mode the user is currently using.', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('aspirant', 'Aspirant'), ('university', 'University')], default='aspirant', help_text='The mode the user registered as first.', max_length=12),
        ),
        migrations.CreateModel(
            name='AspirantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('jamb', 'JAMB UTME'), ('waec', 'WAEC SSCE'), ('neco', 'NECO SSCE'), ('post_utme', 'POST-UTME')], default='jamb', max_length=12)),
                ('target_year', models.PositiveIntegerField(default=2026)),
                ('preferred_subjects', models.JSONField(blank=True, default=list, help_text='List of subject slugs the student is preparing for.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aspirant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aspirant Profile',
                'verbose_name_plural': 'Aspirant Profiles',
            },
        ),
        migrations.CreateModel(
            name='UniversityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('level', models.PositiveIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level'), (600, '600 Level')], default=100)),
                ('current_courses', models.JSONField(blank=True, default=list, help_text='List of course codes the student is currently offering.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='university_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'University Profile',
                'verbose_name_plural': 'University Profiles',
            },
        ),
    ]
