# Generated by Django 5.2.5 on 2026-08-25 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_practicesession_mode_question_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=240)),
                ('category', models.CharField(max_length=30)),
                ('tier', models.CharField(default='field', max_length=20)),
                ('target', models.PositiveIntegerField(default=1)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('registered', 'Registered'), ('signed_in', 'Signed in'), ('signed_out', 'Signed out'), ('session_started', 'Session started'), ('session_completed', 'Session completed'), ('answered', 'Question answered'), ('bookmarked', 'Question bookmarked'), ('badge_earned', 'Badge earned'), ('challenge_created', 'Challenge created'), ('challenge_responded', 'Challenge responded'), ('challenge_completed', 'Challenge completed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='mode',
            field=models.CharField(choices=[('timed', 'Timed Practice'), ('normal', 'Normal Practice'), ('daily', 'Daily Sprint'), ('saved', 'Saved Review'), ('challenge', 'Friend Challenge')], default='timed', max_length=12),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(blank=True, max_length=280)),
                ('subject_label', models.CharField(max_length=120)),
                ('question_payload', models.JSONField(default=list)),
                ('question_count', models.PositiveSmallIntegerField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='learning.subject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('started', 'Started'), ('completed', 'Completed')], default='invited', max_length=12)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('answered_questions', models.PositiveSmallIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('bonus_xp', models.PositiveSmallIntegerField(default=0)),
                ('bonus_awarded_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='learning.challenge')),
                ('practice_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_participation', to='learning.practicesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('invited_at',),
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='learning.badgedefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-earned_at',),
            },
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['starts_at', 'ends_at'], name='learning_ch_starts__a9fa8a_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeparticipant',
            index=models.Index(fields=['user', 'status'], name='learning_ch_user_id_ae081e_idx'),
        ),
        migrations.AddConstraint(
            model_name='challengeparticipant',
            constraint=models.UniqueConstraint(fields=('challenge', 'user'), name='unique_challenge_participant'),
        ),
        migrations.AddConstraint(
            model_name='userbadge',
            constraint=models.UniqueConstraint(fields=('user', 'badge'), name='unique_user_badge'),
        ),
    ]
